namespace MetaSharp.Tests;

/// <summary>
/// End-to-end tests for cross-assembly type discovery + import resolution. A "library"
/// project declares <c>[assembly: TranspileAssembly]</c> + <c>[assembly: EmitPackage(name)]</c>
/// and exposes some types; a "consumer" project references the library and uses one of
/// those types. The expected output is an <c>import { Type } from "&lt;package&gt;/&lt;subpath&gt;"</c>
/// statement, computed from the library's own root namespace.
/// </summary>
public class CrossPackageImportTests
{
    [Test]
    public async Task ConsumerReferencingLibraryType_EmitsCrossPackageImport()
    {
        // Library has two types in different sub-namespaces under "MyLib", so the
        // computed root namespace is "MyLib" and Money's subpath becomes "domain/money".
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@scope/lib")]

            namespace MyLib.Domain
            {
                public record Money(decimal Amount, string Currency);
            }

            namespace MyLib.Other
            {
                public record Marker(string Tag);
            }
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Wallet
            {
                public MyLib.Domain.Money Balance { get; set; } = new(0m, "USD");
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["wallet.ts"];

        // Cross-package import: package name + subpath derived from the library's own
        // root namespace ("MyLib"), so "Domain.Money" becomes "domain/money".
        await Assert.That(output).Contains("import { Money } from \"@scope/lib/domain/money\"");
        await Assert.That(output).Contains("balance: Money");
        // The library type's own .ts file is NOT generated by the consumer's transpilation.
        await Assert.That(result).DoesNotContainKey("money.ts");
    }

    [Test]
    public async Task SameSimpleNameInDifferentAssemblies_DisambiguatedBySymbol()
    {
        // Two `Status` types — one from the library, one from the consumer's own
        // namespace. The library one is referenced by full name; the consumer's local
        // one is used elsewhere. The cross-package import must point to the library
        // version, not be confused with the local one.
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("shared")]

            namespace Shared;

            public enum Status { Active, Inactive }
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public enum Status { Pending, Done }

            public class Order
            {
                public Shared.Status LibStatus { get; set; }
                public Status LocalStatus { get; set; }
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["order.ts"];

        // Cross-package import points at the library's Status, not the local one.
        await Assert.That(output).Contains("import { Status } from \"shared/status\"");
        // Both fields end up using the same TS name `Status` (TypeScript will resolve
        // the ambiguity from the import). The local Status is generated as its own
        // file in the consumer.
        await Assert.That(result).ContainsKey("status.ts");
    }

    [Test]
    public async Task LibraryWithoutEmitPackage_TypeNotImported()
    {
        // Library has [TranspileAssembly] but no [EmitPackage], so its types aren't
        // registered in the cross-assembly map. The consumer references the type but
        // the import collector silently skips it (no string match in any other map).
        // This is the documented behavior pending MS0007 escalation in a follow-up.
        var library = """
            [assembly: TranspileAssembly]

            namespace Lib;

            public record Item(string Name);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Holder
            {
                public Lib.Item? Stored { get; set; }
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["holder.ts"];

        // No import line for Item.
        await Assert.That(output).DoesNotContain("import { Item }");
    }
}
