namespace MetaSharp.Tests;

/// <summary>
/// End-to-end tests for cross-assembly type discovery + import resolution. A "library"
/// project declares <c>[assembly: TranspileAssembly]</c> + <c>[assembly: EmitPackage(name)]</c>
/// and exposes some types; a "consumer" project references the library and uses one of
/// those types. The expected output is an <c>import { Type } from "&lt;package&gt;/&lt;subpath&gt;"</c>
/// statement, computed from the library's own root namespace.
/// </summary>
public class CrossPackageImportTests
{
    [Test]
    public async Task ConsumerReferencingLibraryType_EmitsCrossPackageImport()
    {
        // Library has two types in different sub-namespaces under "MyLib", so the
        // computed root namespace is "MyLib" and Money's subpath becomes "domain/money".
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@scope/lib")]

            namespace MyLib.Domain
            {
                public record Money(decimal Amount, string Currency);
            }

            namespace MyLib.Other
            {
                public record Marker(string Tag);
            }
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Wallet
            {
                public MyLib.Domain.Money Balance { get; set; } = new(0m, "USD");
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["wallet.ts"];

        // Cross-package import: package name + subpath derived from the library's own
        // root namespace ("MyLib"), so "Domain.Money" becomes "domain/money".
        await Assert.That(output).Contains("import { Money } from \"@scope/lib/domain/money\"");
        await Assert.That(output).Contains("balance: Money");
        // The library type's own .ts file is NOT generated by the consumer's transpilation.
        await Assert.That(result).DoesNotContainKey("money.ts");
    }

    [Test]
    public async Task SameSimpleNameInDifferentAssemblies_DisambiguatedBySymbol()
    {
        // Two `Status` types — one from the library, one from the consumer's own
        // namespace. The library one is referenced by full name; the consumer's local
        // one is used elsewhere. The cross-package import must point to the library
        // version, not be confused with the local one.
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("shared")]

            namespace Shared;

            public enum Status { Active, Inactive }
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public enum Status { Pending, Done }

            public class Order
            {
                public Shared.Status LibStatus { get; set; }
                public Status LocalStatus { get; set; }
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["order.ts"];

        // Cross-package import points at the library's Status, not the local one.
        await Assert.That(output).Contains("import { Status } from \"shared/status\"");
        // Both fields end up using the same TS name `Status` (TypeScript will resolve
        // the ambiguity from the import). The local Status is generated as its own
        // file in the consumer.
        await Assert.That(result).ContainsKey("status.ts");
    }

    [Test]
    public async Task LibraryWithoutEmitPackage_EmitsMs0007AtConsumer()
    {
        // Library has [TranspileAssembly] but no [EmitPackage], so its types can't be
        // resolved to a package import. Instead of silently skipping (which would leave
        // the consumer's .ts referencing an unbound name and failing downstream in tsgo),
        // the compiler emits MS0007 at the consumer site explaining what to fix.
        var library = """
            [assembly: TranspileAssembly]

            namespace Lib;

            public record Item(string Name);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Holder
            {
                public Lib.Item? Stored { get; set; }
            }
            """;

        var (files, diagnostics) = TranspileHelper.TranspileWithLibraryAndDiagnostics(library, consumer);
        var output = files["holder.ts"];

        // No import line is generated (we have no package name to import from).
        await Assert.That(output).DoesNotContain("import { Item }");
        // But MS0007 is raised so the user knows what to fix.
        await Assert.That(diagnostics.Any(d =>
            d.Code == "MS0007" && d.Message.Contains("Lib.Item"))).IsTrue();
    }

    [Test]
    public async Task UsedCrossPackages_TrackedForAutoDependencies()
    {
        // After a successful cross-package import, the compiler exposes the package
        // name + source assembly via TypeMapper.UsedCrossPackages. The TypeTransformer
        // formats this into a CrossPackageDependencies dictionary that the CLI driver
        // hands to PackageJsonWriter for the auto-dep merge.
        var library = """
            [assembly: System.Reflection.AssemblyVersion("1.5.2.0")]
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@acme/lib")]

            namespace AcmeLib;

            public record Item(string Name);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Holder
            {
                public AcmeLib.Item? Stored { get; set; }
            }
            """;

        var libCompilation = TranspileHelper.CompileLibrary(library);
        var consumerCompilation = TranspileHelper.CompileConsumer(consumer, libCompilation);

        var transformer = new MetaSharp.Transformation.TypeTransformer(consumerCompilation);
        transformer.TransformAll();

        await Assert.That(transformer.CrossPackageDependencies.ContainsKey("@acme/lib")).IsTrue();
        // Library declares AssemblyVersion 1.5.2.0 → ^1.5.2
        await Assert.That(transformer.CrossPackageDependencies["@acme/lib"]).IsEqualTo("^1.5.2");
    }

    [Test]
    public async Task UnversionedLibrary_GetsWorkspaceDepSpec()
    {
        // No [assembly: AssemblyVersion] → Roslyn defaults to 0.0.0.0 → workspace:*
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@acme/lib")]

            namespace AcmeLib;

            public record Item(string Name);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Holder
            {
                public AcmeLib.Item? Stored { get; set; }
            }
            """;

        var libCompilation = TranspileHelper.CompileLibrary(library);
        var consumerCompilation = TranspileHelper.CompileConsumer(consumer, libCompilation);

        var transformer = new MetaSharp.Transformation.TypeTransformer(consumerCompilation);
        transformer.TransformAll();

        await Assert.That(transformer.CrossPackageDependencies["@acme/lib"]).IsEqualTo("workspace:*");
    }

    [Test]
    public async Task ImportAttributeWithVersion_AddedToDependencies()
    {
        // [Import("Hono", from: "hono", Version = "^4.6.0")] should add `hono` to the
        // tracked dependencies the first time the type is referenced. Without Version,
        // the type still imports correctly but no auto-dep entry is created (the user
        // adds it manually).
        var result = TranspileHelper.Transpile(
            """
            [assembly: TranspileAssembly]

            [Import("Hono", from: "hono", Version = "^4.6.0")]
            public class Hono
            {
                public Hono() { }
            }

            public class App
            {
                public Hono Server { get; } = new Hono();
            }
            """);

        // Use the helper that exposes the transformer's tracked dependencies. We
        // re-compile here so we can read TypeMapper.UsedCrossPackages directly via the
        // CrossPackageDependencies property.
        var compilation = TranspileHelper.CompileLibrary(
            """
            [assembly: TranspileAssembly]

            [Import("Hono", from: "hono", Version = "^4.6.0")]
            public class Hono
            {
                public Hono() { }
            }

            public class App
            {
                public Hono Server { get; } = new Hono();
            }
            """);

        var transformer = new MetaSharp.Transformation.TypeTransformer(compilation);
        transformer.TransformAll();

        await Assert.That(transformer.CrossPackageDependencies.ContainsKey("hono")).IsTrue();
        await Assert.That(transformer.CrossPackageDependencies["hono"]).IsEqualTo("^4.6.0");
        // The generated TS still has the import line.
        await Assert.That(result["app.ts"]).Contains("import { Hono } from \"hono\"");
    }

    [Test]
    public async Task ImportAttributeWithoutVersion_NoAutoDep()
    {
        var compilation = TranspileHelper.CompileLibrary(
            """
            [assembly: TranspileAssembly]

            [Import("Hono", from: "hono")]
            public class Hono { public Hono() { } }

            public class App
            {
                public Hono Server { get; } = new Hono();
            }
            """);

        var transformer = new MetaSharp.Transformation.TypeTransformer(compilation);
        transformer.TransformAll();

        await Assert.That(transformer.CrossPackageDependencies.ContainsKey("hono")).IsFalse();
    }

    [Test]
    public async Task EmitInFile_CrossPackageImportUsesFilePath()
    {
        // The library co-locates Issue + IssueStatus in a single `issue.ts` via
        // [EmitInFile]. The consumer references both types and should produce ONE
        // import line with both names from the file path (not two separate imports
        // by type name).
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@acme/issues")]

            namespace AcmeIssues;

            [EmitInFile("issue")]
            public record Issue(string Title, IssueStatus Status);

            [EmitInFile("issue")]
            public enum IssueStatus { Open, Closed }
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Tracker
            {
                public AcmeIssues.Issue? Current { get; set; }
                public AcmeIssues.IssueStatus Status { get; set; }
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["tracker.ts"];

        // One merged import line, two names, file path is `issue` (not `issue-status`).
        await Assert.That(output).Contains("from \"@acme/issues/issue\"");
        await Assert.That(output).Contains("Issue");
        await Assert.That(output).Contains("IssueStatus");
        // No separate import for issue-status — that file doesn't exist on the lib side.
        await Assert.That(output).DoesNotContain("issue-status");
    }

    [Test]
    public async Task PlainObject_CrossPackage_EmitsAsTypeImport()
    {
        // A [PlainObject] declared in a library and consumed from another project
        // should: (1) emit as a TS interface in the library, (2) flow through the
        // cross-package origin pipeline in the consumer, (3) be imported as
        // type-only since the interface is erased at runtime.
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@acme/dtos")]

            namespace AcmeDtos;

            [PlainObject]
            public record CreateUserDto(string Name, string Email);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Handler
            {
                public AcmeDtos.CreateUserDto? Pending { get; set; }
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["handler.ts"];

        // Type-only cross-package import: the consumer references CreateUserDto only
        // as a type (in a property declaration), so the import must be `import type`
        // to satisfy verbatimModuleSyntax-style consumers.
        await Assert.That(output).Contains("import type { CreateUserDto } from \"@acme/dtos/create-user-dto\"");
        await Assert.That(output).Contains("pending: CreateUserDto | null");
    }

    [Test]
    public async Task PlainObject_CrossPackage_ConstructionLowersToObjectLiteral()
    {
        // When the consumer constructs the cross-package [PlainObject] type via
        // `new T(args)`, the lowering should still produce an object literal — not
        // a class instantiation. The construction is a value usage, so the import
        // is no longer type-only and the consumer can write the object literal
        // referencing the named shape.
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@acme/dtos")]

            namespace AcmeDtos;

            [PlainObject]
            public record CreateUserDto(string Name, string Email);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Factory
            {
                public AcmeDtos.CreateUserDto Make() =>
                    new AcmeDtos.CreateUserDto("Ana", "ana@example.com");
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["factory.ts"];

        await Assert.That(output).Contains("{ name: \"Ana\", email: \"ana@example.com\" }");
        await Assert.That(output).DoesNotContain("new CreateUserDto");
    }

    [Test]
    public async Task ExportFromBclWithVersion_AddedToDependencies()
    {
        // The default decimal mapping in MetaSharp/Runtime/Decimal.cs declares
        // Version = "^10.6.0". Any consumer that uses decimal should auto-get the
        // dependency entry.
        var compilation = TranspileHelper.CompileLibrary(
            """
            [assembly: TranspileAssembly]

            public record Price(decimal Amount);
            """);

        var transformer = new MetaSharp.Transformation.TypeTransformer(compilation);
        transformer.TransformAll();

        await Assert.That(transformer.CrossPackageDependencies.ContainsKey("decimal.js")).IsTrue();
        await Assert.That(transformer.CrossPackageDependencies["decimal.js"]).IsEqualTo("^10.6.0");
    }

    [Test]
    public async Task UnreferencedLibrary_NotInDependencies()
    {
        // The library is referenced as a project dep, but the consumer never uses any
        // of its types. We must NOT add it to dependencies — that would pollute the
        // package.json with unused entries on every regenerate.
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@acme/unused")]

            namespace AcmeUnused;

            public record Unused(int X);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Standalone
            {
                public int Value { get; set; }
            }
            """;

        var libCompilation = TranspileHelper.CompileLibrary(library);
        var consumerCompilation = TranspileHelper.CompileConsumer(consumer, libCompilation);

        var transformer = new MetaSharp.Transformation.TypeTransformer(consumerCompilation);
        transformer.TransformAll();

        await Assert.That(transformer.CrossPackageDependencies.ContainsKey("@acme/unused")).IsFalse();
    }

    [Test]
    public async Task LibraryWithoutEmitPackage_DiagnosticDeduplicates()
    {
        // The same library type referenced from multiple consumer types should produce
        // exactly one MS0007 (deduplicated by type display name).
        var library = """
            [assembly: TranspileAssembly]

            namespace Lib;

            public record Item(string Name);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class HolderA { public Lib.Item? A { get; set; } }
            public class HolderB { public Lib.Item? B { get; set; } }
            public class HolderC { public Lib.Item? C { get; set; } }
            """;

        var (_, diagnostics) = TranspileHelper.TranspileWithLibraryAndDiagnostics(library, consumer);
        var ms0007 = diagnostics.Where(d => d.Code == "MS0007" && d.Message.Contains("Lib.Item")).ToList();
        await Assert.That(ms0007.Count).IsEqualTo(1);
    }
}
