namespace MetaSharp.Tests;

/// <summary>
/// End-to-end tests for cross-assembly type discovery + import resolution. A "library"
/// project declares <c>[assembly: TranspileAssembly]</c> + <c>[assembly: EmitPackage(name)]</c>
/// and exposes some types; a "consumer" project references the library and uses one of
/// those types. The expected output is an <c>import { Type } from "&lt;package&gt;/&lt;subpath&gt;"</c>
/// statement, computed from the library's own root namespace.
/// </summary>
public class CrossPackageImportTests
{
    [Test]
    public async Task ConsumerReferencingLibraryType_EmitsCrossPackageImport()
    {
        // Library has two types in different sub-namespaces under "MyLib", so the
        // computed root namespace is "MyLib" and Money's subpath becomes "domain/money".
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("@scope/lib")]

            namespace MyLib.Domain
            {
                public record Money(decimal Amount, string Currency);
            }

            namespace MyLib.Other
            {
                public record Marker(string Tag);
            }
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Wallet
            {
                public MyLib.Domain.Money Balance { get; set; } = new(0m, "USD");
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["wallet.ts"];

        // Cross-package import: package name + subpath derived from the library's own
        // root namespace ("MyLib"), so "Domain.Money" becomes "domain/money".
        await Assert.That(output).Contains("import { Money } from \"@scope/lib/domain/money\"");
        await Assert.That(output).Contains("balance: Money");
        // The library type's own .ts file is NOT generated by the consumer's transpilation.
        await Assert.That(result).DoesNotContainKey("money.ts");
    }

    [Test]
    public async Task SameSimpleNameInDifferentAssemblies_DisambiguatedBySymbol()
    {
        // Two `Status` types — one from the library, one from the consumer's own
        // namespace. The library one is referenced by full name; the consumer's local
        // one is used elsewhere. The cross-package import must point to the library
        // version, not be confused with the local one.
        var library = """
            [assembly: TranspileAssembly]
            [assembly: EmitPackage("shared")]

            namespace Shared;

            public enum Status { Active, Inactive }
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public enum Status { Pending, Done }

            public class Order
            {
                public Shared.Status LibStatus { get; set; }
                public Status LocalStatus { get; set; }
            }
            """;

        var result = TranspileHelper.TranspileWithLibrary(library, consumer);
        var output = result["order.ts"];

        // Cross-package import points at the library's Status, not the local one.
        await Assert.That(output).Contains("import { Status } from \"shared/status\"");
        // Both fields end up using the same TS name `Status` (TypeScript will resolve
        // the ambiguity from the import). The local Status is generated as its own
        // file in the consumer.
        await Assert.That(result).ContainsKey("status.ts");
    }

    [Test]
    public async Task LibraryWithoutEmitPackage_EmitsMs0007AtConsumer()
    {
        // Library has [TranspileAssembly] but no [EmitPackage], so its types can't be
        // resolved to a package import. Instead of silently skipping (which would leave
        // the consumer's .ts referencing an unbound name and failing downstream in tsgo),
        // the compiler emits MS0007 at the consumer site explaining what to fix.
        var library = """
            [assembly: TranspileAssembly]

            namespace Lib;

            public record Item(string Name);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class Holder
            {
                public Lib.Item? Stored { get; set; }
            }
            """;

        var (files, diagnostics) = TranspileHelper.TranspileWithLibraryAndDiagnostics(library, consumer);
        var output = files["holder.ts"];

        // No import line is generated (we have no package name to import from).
        await Assert.That(output).DoesNotContain("import { Item }");
        // But MS0007 is raised so the user knows what to fix.
        await Assert.That(diagnostics.Any(d =>
            d.Code == "MS0007" && d.Message.Contains("Lib.Item"))).IsTrue();
    }

    [Test]
    public async Task LibraryWithoutEmitPackage_DiagnosticDeduplicates()
    {
        // The same library type referenced from multiple consumer types should produce
        // exactly one MS0007 (deduplicated by type display name).
        var library = """
            [assembly: TranspileAssembly]

            namespace Lib;

            public record Item(string Name);
            """;

        var consumer = """
            [assembly: TranspileAssembly]

            namespace App;

            public class HolderA { public Lib.Item? A { get; set; } }
            public class HolderB { public Lib.Item? B { get; set; } }
            public class HolderC { public Lib.Item? C { get; set; } }
            """;

        var (_, diagnostics) = TranspileHelper.TranspileWithLibraryAndDiagnostics(library, consumer);
        var ms0007 = diagnostics.Where(d => d.Code == "MS0007" && d.Message.Contains("Lib.Item")).ToList();
        await Assert.That(ms0007.Count).IsEqualTo(1);
    }
}
