/**
 * Typed `linq()` — left-to-right composition over a source `Iterable<Src>`
 * via tagged operator descriptors. Each stage takes the previous stage's
 * output as input. Up to 32 stages typed; beyond that falls back to
 * `unknown`.
 *
 * Two consumption shapes:
 *
 * - All composition operators, no terminal → returns `Iterable<R>`.
 *   Lazy + re-enumerable (each `for…of` rewalks).
 * - Final stage is a terminal → returns the terminal's eager result.
 *
 * The stages are descriptor objects (see `types.ts`). At runtime, `linq`
 * calls `stage.apply(acc)` and feeds the result into the next stage. A
 * future IQueryable provider can intercept the same descriptor list and
 * route to SQL / GraphQL / other query backends without touching the
 * runtime call site.
 */
import type { AnyOperator, AnyTerminal, OperatorBase, TerminalBase } from "./types.ts";

/* eslint-disable @typescript-eslint/no-explicit-any */
// Operator-chain overloads (no terminal): result is Iterable<...>

export function linq<Src>(source: Iterable<Src>): Iterable<Src>;
export function linq<Src, A>(source: Iterable<Src>, op1: OperatorBase<Src, A>): Iterable<A>;
export function linq<Src, A, B>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
): Iterable<B>;
export function linq<Src, A, B, C>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
): Iterable<C>;
export function linq<Src, A, B, C, D>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
): Iterable<D>;
export function linq<Src, A, B, C, D, E>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
): Iterable<E>;
export function linq<Src, A, B, C, D, E, F>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
): Iterable<F>;
export function linq<Src, A, B, C, D, E, F, G>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
): Iterable<G>;
export function linq<Src, A, B, C, D, E, F, G, H>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
): Iterable<H>;
export function linq<Src, A, B, C, D, E, F, G, H, I>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
): Iterable<I>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
): Iterable<J>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
): Iterable<K>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
): Iterable<L>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
): Iterable<M>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
): Iterable<N>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
): Iterable<O>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
): Iterable<P>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
): Iterable<Q>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
): Iterable<R>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
): Iterable<S>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
): Iterable<T>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
): Iterable<U>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
): Iterable<V>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
): Iterable<W>;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
): Iterable<X>;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
): Iterable<Y>;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
): Iterable<Z>;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
): Iterable<AA>;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
): Iterable<AB>;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
  op29: OperatorBase<AB, AC>,
): Iterable<AC>;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
  op29: OperatorBase<AB, AC>,
  op30: OperatorBase<AC, AD>,
): Iterable<AD>;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
  op29: OperatorBase<AB, AC>,
  op30: OperatorBase<AC, AD>,
  op31: OperatorBase<AD, AE>,
): Iterable<AE>;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
  op29: OperatorBase<AB, AC>,
  op30: OperatorBase<AC, AD>,
  op31: OperatorBase<AD, AE>,
  op32: OperatorBase<AE, AF>,
): Iterable<AF>;

// Terminal-final overloads: chain ends with TerminalBase<_, R>

export function linq<Src, A>(source: Iterable<Src>, op1: TerminalBase<Src, A>): A;
export function linq<Src, A, B>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: TerminalBase<A, B>,
): B;
export function linq<Src, A, B, C>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: TerminalBase<B, C>,
): C;
export function linq<Src, A, B, C, D>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: TerminalBase<C, D>,
): D;
export function linq<Src, A, B, C, D, E>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: TerminalBase<D, E>,
): E;
export function linq<Src, A, B, C, D, E, F>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: TerminalBase<E, F>,
): F;
export function linq<Src, A, B, C, D, E, F, G>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: TerminalBase<F, G>,
): G;
export function linq<Src, A, B, C, D, E, F, G, H>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: TerminalBase<G, H>,
): H;
export function linq<Src, A, B, C, D, E, F, G, H, I>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: TerminalBase<H, I>,
): I;
export function linq<Src, A, B, C, D, E, F, G, H, I, J>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: TerminalBase<I, J>,
): J;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: TerminalBase<J, K>,
): K;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: TerminalBase<K, L>,
): L;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: TerminalBase<L, M>,
): M;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: TerminalBase<M, N>,
): N;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: TerminalBase<N, O>,
): O;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: TerminalBase<O, P>,
): P;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: TerminalBase<P, Q>,
): Q;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: TerminalBase<Q, R>,
): R;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: TerminalBase<R, S>,
): S;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: TerminalBase<S, T>,
): T;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: TerminalBase<T, U>,
): U;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: TerminalBase<U, V>,
): V;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: TerminalBase<V, W>,
): W;
export function linq<Src, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: TerminalBase<W, X>,
): X;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: TerminalBase<X, Y>,
): Y;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: TerminalBase<Y, Z>,
): Z;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: TerminalBase<Z, AA>,
): AA;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: TerminalBase<AA, AB>,
): AB;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
  op29: TerminalBase<AB, AC>,
): AC;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
  op29: OperatorBase<AB, AC>,
  op30: TerminalBase<AC, AD>,
): AD;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
  op29: OperatorBase<AB, AC>,
  op30: OperatorBase<AC, AD>,
  op31: TerminalBase<AD, AE>,
): AE;
export function linq<
  Src,
  A,
  B,
  C,
  D,
  E,
  F,
  G,
  H,
  I,
  J,
  K,
  L,
  M,
  N,
  O,
  P,
  Q,
  R,
  S,
  T,
  U,
  V,
  W,
  X,
  Y,
  Z,
  AA,
  AB,
  AC,
  AD,
  AE,
  AF,
>(
  source: Iterable<Src>,
  op1: OperatorBase<Src, A>,
  op2: OperatorBase<A, B>,
  op3: OperatorBase<B, C>,
  op4: OperatorBase<C, D>,
  op5: OperatorBase<D, E>,
  op6: OperatorBase<E, F>,
  op7: OperatorBase<F, G>,
  op8: OperatorBase<G, H>,
  op9: OperatorBase<H, I>,
  op10: OperatorBase<I, J>,
  op11: OperatorBase<J, K>,
  op12: OperatorBase<K, L>,
  op13: OperatorBase<L, M>,
  op14: OperatorBase<M, N>,
  op15: OperatorBase<N, O>,
  op16: OperatorBase<O, P>,
  op17: OperatorBase<P, Q>,
  op18: OperatorBase<Q, R>,
  op19: OperatorBase<R, S>,
  op20: OperatorBase<S, T>,
  op21: OperatorBase<T, U>,
  op22: OperatorBase<U, V>,
  op23: OperatorBase<V, W>,
  op24: OperatorBase<W, X>,
  op25: OperatorBase<X, Y>,
  op26: OperatorBase<Y, Z>,
  op27: OperatorBase<Z, AA>,
  op28: OperatorBase<AA, AB>,
  op29: OperatorBase<AB, AC>,
  op30: OperatorBase<AC, AD>,
  op31: OperatorBase<AD, AE>,
  op32: TerminalBase<AE, AF>,
): AF;

export function linq(
  source: unknown,
  ...ops: (OperatorBase<any, any> | TerminalBase<any, any>)[]
): unknown {
  const result = ops.reduce((acc, op) => op.apply(acc as Iterable<any>) as any, source as any);
  // Attach the original stage list to the materialized result so an
  // IQueryable-style consumer can introspect the chain. Skipped for
  // primitive results (terminals like `count` / `sum` return numbers
  // / booleans where defineProperty would throw).
  if (result !== null && typeof result === "object") {
    try {
      Object.defineProperty(result, LINQ_STAGES, {
        value: ops,
        enumerable: false,
        configurable: true,
      });
    } catch {
      // Frozen objects (e.g. a consumer's pre-frozen Iterable) silently
      // fall through; introspection will not be available but the
      // closure path still works.
    }
  }
  return result;
}

/**
 * Symbol-keyed slot the runtime attaches to every object-typed result
 * of {@link linq} so an introspecting consumer (IQueryable provider,
 * query planner, debugger) can read the descriptor chain without
 * reaching for closures or hand-rolling a capture helper. Scoped via
 * `Symbol.for` so multiple module copies (e.g. duplicate npm
 * resolutions) share the slot.
 */
export const LINQ_STAGES = Symbol.for("metano-runtime/system/linq:stages");

/**
 * Reads the descriptor chain attached by {@link linq} on a query
 * result. Returns `undefined` when the value is a primitive, was
 * produced outside this runtime, or had introspection suppressed.
 */
export function getStages(query: unknown): Stage[] | undefined {
  if (query === null || typeof query !== "object") return undefined;
  const value = (query as Record<symbol, unknown>)[LINQ_STAGES];
  return Array.isArray(value) ? (value as Stage[]) : undefined;
}

/**
 * Helper that exposes the raw descriptor chain to an introspecting
 * consumer when the chain has not yet been handed to {@link linq}.
 * Returns the stages verbatim so the consumer can switch on `kind`
 * and read the captured lambdas + parameters.
 */
export type Stage = AnyOperator | AnyTerminal;

export function stages(...ops: Stage[]): Stage[] {
  return ops;
}
/* eslint-enable @typescript-eslint/no-explicit-any */
