<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <MetanoOutputDir>../../targets/js/sample-counter-v5/src/</MetanoOutputDir>
    <MetanoFilePrefix>/** biome-ignore-all lint/complexity/noUselessConstructor: explicit shape preserved by transpiler */</MetanoFilePrefix>
    <MetanoCompilerProject>../../src/Metano.Compiler.TypeScript/Metano.Compiler.TypeScript.csproj</MetanoCompilerProject>
    <MetanoPostBuildCommand>bunx biome check --write &quot;$(MetanoOutputDir)&quot;</MetanoPostBuildCommand>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Metano/Metano.csproj" PrivateAssets="all" />
    <ProjectReference Include="../../bindings/Metano.TypeScript.DOM/Metano.TypeScript.DOM.csproj" />
    <ProjectReference Include="..\..\bindings\Metano.TypeScript.SolidJs\Metano.TypeScript.SolidJs.csproj" />
  </ItemGroup>

  <Import Project="../../src/Metano.Build/build/Metano.Build.targets" />
</Project>
